### PR TITLE
feat(v26): Zod plugin: Patch Zod's CJS

### LINKED ISSUE #2981: v25: example is not a function
# Description

Upgrading from v24 to v25 appears to break examples in generated documentation. I created a git repo which reproduces this issue: https://github.com/squishykid/express-zod-api-example-issue

There are two ways this library allows developers to provide examples:
- `.example()`
- `.meta()`

Upon upgrading from 24.7.3 to 25.0.0 it appears that both of these methods of providing examples break in different ways.

Examples supplied via the .meta() method simply vanish silently from the generated documentation. Perhaps zod's `globalRegistry` is not as global any more? I notice that examples (default error messages) added by this library continue to be included in the documentation yaml output.

Examples supplied via the `.example()` method cause a compile error after upgrading from v24.7.3 to v25.0.0:
```
}).example({ name: 'bingo' });
   ^

TypeError: zod_1.z.object(...).example is not a function
```

## Expected

I would have expeted `.example()` and `.meta()` to both produce examples in the documentation output, regardless of using v24.x or v25.x of this library.

## Reproduction

I have created a repository here which extends a previous minimal example for zod bugs.

The repo currently uses v24.7.3, but upon upgrading to v25.0.0 the bug will be triggered.

https://github.com/squishykid/express-zod-api-example-issue

## Context

- Node.js version: 22.20.0
- `express-zod-api` version: v24.7.3 to v25.0.0

### PR DESCRIPTION
**Pull request by RobinTail**
Fixes #2981 

After fixing `globalRegistry` by #3086 , it could be now considered to address the dual package hazard completely.
For that I'm trying to make Zod plugin patch both CJS and ESM exports of Zod, so that it would no matter which environment user runs the framework.

## Summary by CodeRabbit

* **Bug Fixes**
  * Resolved TypeError in CommonJS environments by extending Zod's CJS exports.

* **Documentation**
  * Removed ESM-only requirements and related error notes from documentation.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by RobinTail** [comment]
I consider the experiment a success

**Comment by RobinTail** [comment]
✅ QAed against the example repo https://github.com/squishykid/express-zod-api-example-issue mentioned in #2981

**Comment by RobinTail** [comment]
@coderabbitat review

File: zod-plugin/CHANGELOG.md [hunk 1]
```diff
@@ -4,7 +4,8 @@
 
 ### v3.0.0
 
-- Supported `zod` versions: `^4.1.13`.
+- Supported `zod` versions: `^4.1.13`;
+- The plugin patches both ESM and CJS exports of `zod`.
```
Comment (RobinTail) [inline zod-plugin/CHANGELOG.md]:
```suggestion
- The plugin now also patches the CJS exports of `zod`.
```

**Comment by RobinTail** [comment]
ready
