### PR TITLE
fix(docs): Add ESM requirements

### LINKED ISSUE #2981: v25: example is not a function
# Description

Upgrading from v24 to v25 appears to break examples in generated documentation. I created a git repo which reproduces this issue: https://github.com/squishykid/express-zod-api-example-issue

There are two ways this library allows developers to provide examples:
- `.example()`
- `.meta()`

Upon upgrading from 24.7.3 to 25.0.0 it appears that both of these methods of providing examples break in different ways.

Examples supplied via the .meta() method simply vanish silently from the generated documentation. Perhaps zod's `globalRegistry` is not as global any more? I notice that examples (default error messages) added by this library continue to be included in the documentation yaml output.

Examples supplied via the `.example()` method cause a compile error after upgrading from v24.7.3 to v25.0.0:
```
}).example({ name: 'bingo' });
   ^

TypeError: zod_1.z.object(...).example is not a function
```

## Expected

I would have expeted `.example()` and `.meta()` to both produce examples in the documentation output, regardless of using v24.x or v25.x of this library.

## Reproduction

I have created a repository here which extends a previous minimal example for zod bugs.

The repo currently uses v24.7.3, but upon upgrading to v25.0.0 the bug will be triggered.

https://github.com/squishykid/express-zod-api-example-issue

## Context

- Node.js version: 22.20.0
- `express-zod-api` version: v24.7.3 to v25.0.0

### PR DESCRIPTION
**Pull request by RobinTail**
closes #2981

## Summary by CodeRabbit

* **Documentation**
  * Reordered README contents and added a new "TypeError: example is not a function" caveat with links to environment guidance.
  * Updated setup guidance to prioritize ESM usage and explicit compiler options.
  * Simplified and reformatted examples and code snippets for clarity and consistency.

* **Changelog**
  * Added v25.5.3 entry and refined prior releases with updated ESM guidance.

* **Contributors**
  * Added contributor badges/entries.

### CODE REVIEW

**Comment by RobinTail** [comment]
@coderabbitai, the cause of the issue is described here: https://github.com/RobinTail/express-zod-api/issues/2981#issuecomment-3360464495

**Comment by RobinTail** [comment]
@coderabbitai, `compilerOptions` do not make it ESM, only `type` in `package.json` or `mts`/`mjs` extension does. Alternative way is to run the cosumer's code using `tsx` or `vite-node` that use their own compilers.

File: README.md [hunk 1]
```diff
@@ -183,9 +183,13 @@ pnpm add -D @types/express @types/node @types/http-errors
 
 ## Environment preparation
 
-Consider using the recommended `tsconfig.json` base for your project according to your Node.js version,
-for example [the base for Node.js 20+](https://github.com/tsconfig/bases/blob/main/bases/node20.json).
-Ensure having the following options in order to make it work as expected:
+Starting v25, ensure running your code as ESM module by either:
```
Comment (RobinTail) [inline README.md]:
```suggestion
Starting v25, ensure running your code as ESM by either:
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -75,9 +85,10 @@ const config = createConfig({
 - Supported Node.js versions: `^20.19.0 || ^22.12.0 || ^24.0.0`;
 - The framework distribution is now ESM-only (finally);
   - All the Node.js versions listed above support `require(ESM)` syntax;
-  - If facing TypeScript error `TS1479`, ensure either:
-    - using the [recommended tsconfig base for Node 20+](https://github.com/tsconfig/bases/blob/main/bases/node20.json);
-    - or switching your project to ESM by setting `"type": "module"` in `package.json`;
+  - If facing TypeScript error `TS1479`:
+    - switch your project to ESM by setting `"type": "module"` in `package.json`;
+    - or change file extension to `.mts`;
+    - or run your code using `tsx` or `vite-node` or similar tool;
```
Comment (RobinTail) [inline CHANGELOG.md]:
```suggestion
  - If facing TypeScript error `TS1479`, ensure either:
    - using the [recommended tsconfig base for Node 20+](https://github.com/tsconfig/bases/blob/main/bases/node20.json);
    - or switching your project to ESM by setting `"type": "module"` in `package.json`;
```
