### ISSUE TITLE
v25: example is not a function

### ISSUE THREAD

**Issue by squishykid** [RobinTail/express-zod-api#2981]
# Description

Upgrading from v24 to v25 appears to break examples in generated documentation. I created a git repo which reproduces this issue: https://github.com/squishykid/express-zod-api-example-issue

There are two ways this library allows developers to provide examples:
- `.example()`
- `.meta()`

Upon upgrading from 24.7.3 to 25.0.0 it appears that both of these methods of providing examples break in different ways.

Examples supplied via the .meta() method simply vanish silently from the generated documentation. Perhaps zod's `globalRegistry` is not as global any more? I notice that examples (default error messages) added by this library continue to be included in the documentation yaml output.

Examples supplied via the `.example()` method cause a compile error after upgrading from v24.7.3 to v25.0.0:
```
}).example({ name: 'bingo' });
   ^

TypeError: zod_1.z.object(...).example is not a function
```

## Expected

I would have expeted `.example()` and `.meta()` to both produce examples in the documentation output, regardless of using v24.x or v25.x of this library.

## Reproduction

I have created a repository here which extends a previous minimal example for zod bugs.

The repo currently uses v24.7.3, but upon upgrading to v25.0.0 the bug will be triggered.

https://github.com/squishykid/express-zod-api-example-issue

## Context

- Node.js version: 22.20.0
- `express-zod-api` version: v24.7.3 to v25.0.0

**Comment by squishykid** [comment]
@dosu it seems that I am already using the example/meta API in the way you are suggesting for v25. It seems like this is actually a bug. Please see my linked reproduction repository.

**Comment by RobinTail** [comment]
@squishykid , I checked your repo, it can be fixed by adding the following line to your `package.json`:

```json lines
  "type": "module",
```

Not sure yet why.
Related PR #2741

**Comment by RobinTail** [comment]
I think I figured this out, @squishykid .

- v25 is ESM only built version of Express Zod API
- Express Zod API `import`s Zod and patches it by installing the `.example()` method
- The code in your repo is CommonJS because `package.json` lacks `type: module`
- Zod exports two bundles: CJS and ESM
- So when your compiled `dist/index.js` operates `z.object` it's the `require`d one, but not the one patched

So, `require(ESM)` works fine between your code and Express Zod API, but there is a deviation between how your code and Express Zod API refer to Zod.

@dosu learn

**Comment by RobinTail** [comment]
The issue retained in latest of v25 where the installation of `.example` method was extracted into a separate package `@express-zod-api/zod-plugin`, see #2869 
Perhaps, it that package should still provide CJS bundle while Zod does, so that we could fix this problem.

**Comment by RobinTail** [comment]
It seems that we're facing the classic example of [Dual Package Hazard](https://nodejs.org/download/release/v15.2.0/docs/api/packages.html#packages_dual_package_hazard) here

**Comment by RobinTail** [comment]
> Examples supplied via the .meta() method simply vanish silently from the generated documentation
> Perhaps zod's globalRegistry is not as global any more?

I think it's caused by the same issue — there might be two `globalRegistry`, one for each Zod's bundle — CJS and ESM copy.
Your repo operates the CJS one (because the code transformed to `require()`), while the framework reads from the ESM one while making the documentation (because the framework uses `import` statement), @squishykid 

Zod release files:

<img width="895" height="509" alt="Image" src="https://github.com/user-attachments/assets/9e2ab9dc-84d4-4b25-b161-c0bde5a21477" />

**Comment by squishykid** [comment]
Thank you for looking into this, I can confirm it was resolved by setting  `"type": "module",` in package.json. And all of this does match up with the 'dual package hazzard' as described.

I did see some discussion regarding `"type": "module",` in other issues, but for some reason I thought it was a typescript compiler option. I didn't realise this was something to be set in package.json.

Not sure if this is actually a bug then, sounds like I was just using the library incorrectly.

**Comment by squishykid** [comment]
Although I see now that #2982 was created. Will that change resolve the issue without requiring `"type": "module"`?

**Comment by RobinTail** [comment]
> #2982 Will that change resolve the issue without requiring `"type": "module"`?

It turned out that no. Though, it's possible to fix it partially (the `example` method) by installing and importing the proposed beta version directly and in a certain order, BUT, and this is a huge one: it would not fix the essence of this issue causing another part that you found (regarding the `meta` method and `globalRegistry` of Zod itself).
It could be fixed by reintroducing CJS built of the framework, but I'd like to avoid that, because ESM is the modern standard we all should adopt now.
Also, I'd like to point out that it's possible to avoid this issue by running your code from sources using `tsx`, `vite-node` or similar tool, @squishykid

**Comment by RobinTail** [comment]
Found one more way to do it without `type: "module"`, @squishykid : 

- Rename your `index.ts` to `index.mts` :) 
- And run the compiled code as `node dist/index.mjs`

**Comment by squishykid** [comment]
That is a really interesting option! Though I think this is the kick we need to upgrade to modules.

Thank you for looking at this in such depth!

**Comment by RobinTail** [comment]
This issue is about to be properly fixed in upcoming v26: #2939
